"""
Exception handling system for rules-emerging-pattern.

Provides multi-level escalation protocols, multi-channel user notifications,
error classification, automated remediation, and incident management.
"""

from validation_systems.exception_handling.escalation_protocols import (
    EscalationProtocols,
    EscalationLevel,
    EscalationChannel,
    EscalationTriggerType,
    EscalationStatus,
    SLARisk,
    SLADefinition,
    EscalationTrigger,
    EscalationRoute,
    EscalationRecord,
    ProtocolConfig,
)

from validation_systems.exception_handling.user_notification import (
    UserNotification,
    NotificationChannel,
    NotificationPriority,
    NotificationStatus,
    DeliveryMethod,
    NotificationPreference,
    NotificationTemplate,
    RenderedNotification,
    DeliveryReceipt,
    NotificationRecord,
    BatchConfig,
    RateLimiterConfig,
    DeliveryProvider,
    ConsoleDeliveryProvider,
    LoggingDeliveryProvider,
)

from validation_systems.exception_handling.error_classifier import (
    ErrorClassifier,
    ErrorType,
    ClassificationMethod,
    ErrorGroupStatus,
    ClassificationRule,
    ClassificationResult,
    ErrorGroup,
    ErrorClassifierConfig,
)

from validation_systems.exception_handling.remediation_handler import (
    RemediationHandler,
    RemediationActionType,
    RemediationStatus,
    SafetyCheckResult,
    RemediationAction,
    RemediationRecord,
    RollbackRecord,
    RemediationWorkflow,
)

from validation_systems.exception_handling.incident_manager import (
    IncidentManager,
    IncidentPriority,
    IncidentStatus,
    IncidentCategory,
    RCAStatus,
    Incident,
    IncidentEvent,
    IncidentNote,
    ActionItem,
    RootCauseAnalysis,
    IncidentConfig,
)

__all__ = [
    "EscalationProtocols",
    "EscalationLevel",
    "EscalationChannel",
    "EscalationTriggerType",
    "EscalationStatus",
    "SLARisk",
    "SLADefinition",
    "EscalationTrigger",
    "EscalationRoute",
    "EscalationRecord",
    "ProtocolConfig",
    "UserNotification",
    "NotificationChannel",
    "NotificationPriority",
    "NotificationStatus",
    "DeliveryMethod",
    "NotificationPreference",
    "NotificationTemplate",
    "RenderedNotification",
    "DeliveryReceipt",
    "NotificationRecord",
    "BatchConfig",
    "RateLimiterConfig",
    "DeliveryProvider",
    "ConsoleDeliveryProvider",
    "LoggingDeliveryProvider",
    "ErrorClassifier",
    "ErrorType",
    "ClassificationMethod",
    "ErrorGroupStatus",
    "ClassificationRule",
    "ClassificationResult",
    "ErrorGroup",
    "ErrorClassifierConfig",
    "RemediationHandler",
    "RemediationActionType",
    "RemediationStatus",
    "SafetyCheckResult",
    "RemediationAction",
    "RemediationRecord",
    "RollbackRecord",
    "RemediationWorkflow",
    "IncidentManager",
    "IncidentPriority",
    "IncidentStatus",
    "IncidentCategory",
    "RCAStatus",
    "Incident",
    "IncidentEvent",
    "IncidentNote",
    "ActionItem",
    "RootCauseAnalysis",
    "IncidentConfig",
]
