"""Default safety patterns organized by category."""

from typing import Dict, List, Any

SAFETY_PATTERNS: Dict[str, List[Dict[str, Any]]] = {
    "child_safety": [
        {
            "name": "child_exploitation",
            "regex": r"(child\s*(exploit|abuse|pornogr|trafficking|grooming))",
            "severity": "critical",
            "description": "Child exploitation content",
            "action": "escalate",
        },
        {
            "name": "minor_protection",
            "regex": r"(underage\s*(content|sexual|explicit)|minor\s*abuse)",
            "severity": "critical",
            "description": "Minor protection violation",
            "action": "escalate",
        },
        {
            "name": "csam_reference",
            "regex": r"(csam|child\s*s[ae]xual\s*abuse\s*material)",
            "severity": "critical",
            "description": "CSAM reference detected",
            "action": "escalate",
        },
        {
            "name": "child_luring",
            "regex": r"(luring\s*(minor|child|teen)|solicit\s*(minor|underage))",
            "severity": "critical",
            "description": "Child luring behavior",
            "action": "escalate",
        },
        {
            "name": "child_labor",
            "regex": r"(child\s*(labor|labour|exploitation|slavery|traffick))",
            "severity": "critical",
            "description": "Child labor exploitation",
            "action": "escalate",
        },
        {
            "name": "minor_explicit_imagery",
            "regex": r"(nude\s*(minor|underage|child|teen)|minor\s*nudity)",
            "severity": "critical",
            "description": "Minor explicit imagery reference",
            "action": "escalate",
        },
    ],
    "weapons": [
        {
            "name": "weapon_manufacturing",
            "regex": r"(how\s*to\s*(build|make|manufacture|3d\s*print)\s*(a\s*)?(gun|firearm|weapon|bomb|explosive))",
            "severity": "critical",
            "description": "Weapon manufacturing instructions",
            "action": "block",
        },
        {
            "name": "explosive_instructions",
            "regex": r"(explosive\s*(device|material|compound|preparation)|bomb[- ]?making)",
            "severity": "critical",
            "description": "Explosive device instructions",
            "action": "block",
        },
        {
            "name": "chemical_weapons",
            "regex": r"(chemical\s*(weapon|warfare|agent)|sarin|vx\s*agent|mustard\s*gas)",
            "severity": "critical",
            "description": "Chemical weapons reference",
            "action": "block",
        },
        {
            "name": "biological_weapons",
            "regex": r"(biological\s*(weapon|agent|warfare)|weaponize\s*(virus|bacteria|toxin))",
            "severity": "critical",
            "description": "Biological weapons reference",
            "action": "block",
        },
        {
            "name": "firearm_trafficking",
            "regex": r"(firearm\s*(trafficking|smuggling)|illegal\s*(gun|firearm)\s*(sale|trade|purchase))",
            "severity": "high",
            "description": "Firearm trafficking",
            "action": "block",
        },
        {
            "name": "weapon_modification",
            "regex": r"(how\s*to\s*(modify|convert|unlock|make\s*fully\s*automatic)\s*(a\s*)?(gun|firearm|weapon))",
            "severity": "high",
            "description": "Weapon modification instructions",
            "action": "block",
        },
    ],
    "self_harm": [
        {
            "name": "suicide_methods",
            "regex": r"(suicide\s*(method|technique|how\s*to)|kill\s*yourself|commit\s*suicide)",
            "severity": "critical",
            "description": "Suicide method content",
            "action": "escalate",
        },
        {
            "name": "self_harm_instructions",
            "regex": r"(self[- ]?harm\s*(method|technique|way)|cut\s*yourself|harm\s*yourself)",
            "severity": "high",
            "description": "Self-harm instructions",
            "action": "escalate",
        },
        {
            "name": "eating_disorder_harm",
            "regex": r"(pro[- ]?(ana|mia|bulimia)|(anorexia|bulimia)\s*(tips|method|how\s*to)|thinspiration)",
            "severity": "high",
            "description": "Eating disorder harmful content",
            "action": "escalate",
        },
        {
            "name": "suicide_encouragement",
            "regex": r"(you\s*should\s*(kill|harm)\s*yourself|just\s*(kill|end)\s*it|better\s*off\s*dead)",
            "severity": "critical",
            "description": "Suicide encouragement",
            "action": "escalate",
        },
        {
            "name": "self_harm_glorification",
            "regex": r"(self[- ]?harm\s*(is\s*beautiful|glorif|pride)|cutting\s*(pride|awareness\s*day))",
            "severity": "medium",
            "description": "Self-harm glorification",
            "action": "warn",
        },
    ],
    "violence": [
        {
            "name": "mass_violence",
            "regex": r"(mass\s*(shooting|murder|killing|violence)|school\s*shooting\s*plan)",
            "severity": "critical",
            "description": "Mass violence content",
            "action": "block",
        },
        {
            "name": "graphic_violence",
            "regex": r"(graphic\s*(violence|gore|torture|mutilation)|extreme\s*cruelty)",
            "severity": "high",
            "description": "Graphic violence content",
            "action": "block",
        },
        {
            "name": "violent_attack_instructions",
            "regex": r"(how\s*to\s*(attack|assault|stab|shoot)\s*(someone|people|a\s*person))",
            "severity": "critical",
            "description": "Violent attack instructions",
            "action": "block",
        },
        {
            "name": "domestic_violence",
            "regex": r"(domestic\s*(violence|abuse|battery)|spousal\s*abuse|wife\s*beating)",
            "severity": "high",
            "description": "Domestic violence content",
            "action": "block",
        },
        {
            "name": "gang_violence",
            "regex": r"(gang[- ]?(related|violence|warfare|shooting|initiation))",
            "severity": "high",
            "description": "Gang violence content",
            "action": "block",
        },
    ],
    "terrorism": [
        {
            "name": "terrorist_activity",
            "regex": r"(terrorist\s*(attack|act|recruitment|training|cell)|join\s*(isis|isil|al[- ]?qaeda|hamas|hezbollah))",
            "severity": "critical",
            "description": "Terrorist activity content",
            "action": "escalate",
        },
        {
            "name": "extremist_ideology",
            "regex": r"(extremist\s*(ideology|propaganda|recruitment)|radicalization\s*(guide|manual|technique))",
            "severity": "critical",
            "description": "Extremist ideology propagation",
            "action": "escalate",
        },
        {
            "name": "terrorist_financing",
            "regex": r"(terrorist\s*(financing|funding|donation)|fund\s*terrorism)",
            "severity": "critical",
            "description": "Terrorist financing",
            "action": "escalate",
        },
    ],
    "drugs": [
        {
            "name": "illegal_drug_manufacturing",
            "regex": r"(how\s*to\s*(make|manufacture|synthesize|cook)\s*(meth|heroin|cocaine|lsd|fentanyl|ecstasy))",
            "severity": "high",
            "description": "Illegal drug manufacturing",
            "action": "block",
        },
        {
            "name": "drug_trafficking",
            "regex": r"(drug\s*(trafficking|smuggling|dealing|distribution|cartel))",
            "severity": "high",
            "description": "Drug trafficking content",
            "action": "block",
        },
        {
            "name": "drug_promotion",
            "regex": r"(buy\s*(weed|cocaine|heroin|meth|lsd|ecstasy|fentanyl)\s*online)",
            "severity": "medium",
            "description": "Drug promotion/sale",
            "action": "block",
        },
        {
            "name": "prescription_drug_abuse",
            "regex": r"(buy\s*(prescription|medication|pill)\s*(without|no\s*script|online\s*no\s*Rx))",
            "severity": "medium",
            "description": "Prescription drug abuse",
            "action": "warn",
        },
    ],
    "hate_speech": [
        {
            "name": "racial_slurs",
            "regex": r"\b(n[io]gg[ae]r|k[iy]ke|sp[iy]c|ch[i1]nk|w[eo]g|gook|paki)\b",
            "severity": "high",
            "description": "Racial slurs detected",
            "action": "block",
        },
        {
            "name": "hate_group_propaganda",
            "regex": r"(white\s*supremacy|neo[- ]?nazi|racial\s*purity|ethnic\s*cleansing|genocide\s*advocacy)",
            "severity": "critical",
            "description": "Hate group propaganda",
            "action": "block",
        },
        {
            "name": "religious_hate",
            "regex": r"(religious\s*(hatred|intolerance|persecution)|islamophobi|antisemit|christianophobi)",
            "severity": "high",
            "description": "Religious hatred",
            "action": "block",
        },
        {
            "name": "lgbtq_hate",
            "regex": r"(lgbtq?\s*(hatred|propaganda|agenda|recruitment)|homophobi|transphobi)",
            "severity": "high",
            "description": "LGBTQ+ hate speech",
            "action": "block",
        },
    ],
    "harassment": [
        {
            "name": "threats_of_violence",
            "regex": r"(i\s*(will|am\s*going\s*to)\s*(kill|hurt|harm|attack)\s*(you|him|her|them|someone))",
            "severity": "high",
            "description": "Direct threats of violence",
            "action": "escalate",
        },
        {
            "name": "stalking_content",
            "regex": r"(stalking\s*(you|someone|victim)|track\s*(your|someone'?s)\s*(location|movement|whereabouts))",
            "severity": "high",
            "description": "Stalking behavior",
            "action": "escalate",
        },
        {
            "name": "doxing_threats",
            "regex": r"(dox\s*(you|someone)|leak\s*(address|phone|personal\s*info)|reveal\s*(location|identity))",
            "severity": "high",
            "description": "Doxing threats",
            "action": "escalate",
        },
        {
            "name": "sexual_harassment",
            "regex": r"(sexual\s*(harassment|coercion|extortion)|sextortion|revenge\s*porn)",
            "severity": "high",
            "description": "Sexual harassment",
            "action": "escalate",
        },
    ],
    "explicit_content": [
        {
            "name": "explicit_sexual",
            "regex": r"(explicit\s*(sexual|adult|content)|pornographic|hardcore\s*(content|material))",
            "severity": "medium",
            "description": "Explicit sexual content",
            "action": "redact",
        },
        {
            "name": "obscenity",
            "regex": r"\b(fuck|shit|asshole|bitch|cunt|dick|piss|motherfucker)\b",
            "severity": "low",
            "description": "Profanity detected",
            "action": "warn",
        },
        {
            "name": "erotica",
            "regex": r"(erotic\s*(story|fiction|content)|adult\s*(story|fiction))",
            "severity": "medium",
            "description": "Erotic content",
            "action": "warn",
        },
    ],
    "personal_info": [
        {
            "name": "ssn_pattern",
            "regex": r"\b\d{3}[-]\d{2}[-]\d{4}\b",
            "severity": "high",
            "description": "Social Security Number detected",
            "action": "redact",
        },
        {
            "name": "credit_card_pattern",
            "regex": r"\b(?:\d[ -]*?){13,16}\b",
            "severity": "high",
            "description": "Potential credit card number detected",
            "action": "redact",
        },
        {
            "name": "phone_number",
            "regex": r"\b\d{3}[-.]?\d{3}[-.]?\d{4}\b",
            "severity": "medium",
            "description": "Phone number detected",
            "action": "redact",
        },
        {
            "name": "email_address",
            "regex": r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b",
            "severity": "medium",
            "description": "Email address detected",
            "action": "redact",
        },
        {
            "name": "bank_account",
            "regex": r"\b\d{8,17}\b",
            "severity": "high",
            "description": "Potential bank account number",
            "action": "redact",
        },
    ],
    "fraud": [
        {
            "name": "phishing_content",
            "regex": r"(verify\s*(your\s*)?(account|bank|credit\s*card|paypal)\s*(details|information|password))",
            "severity": "high",
            "description": "Phishing content detected",
            "action": "block",
        },
        {
            "name": "scam_patterns",
            "regex": r"(you'?ve\s*won\s*(\d+|a\s*prize)|claim\s*your\s*prize|send\s*money\s*to\s*receive|advance\s*fee\s*scam)",
            "severity": "high",
            "description": "Financial scam detected",
            "action": "block",
        },
        {
            "name": "identity_theft",
            "regex": r"(identity\s*(theft|fraud|steal)|steal\s*(identity|personally\s*identifiable))",
            "severity": "high",
            "description": "Identity theft content",
            "action": "block",
        },
        {
            "name": "investment_fraud",
            "regex": r"(guaranteed\s*returns|get\s*rich\s*quick|pump\s*and\s*dump|pyramid\s*scheme|ponzi)",
            "severity": "high",
            "description": "Investment fraud detected",
            "action": "block",
        },
    ],
    "malware": [
        {
            "name": "malware_instructions",
            "regex": r"(how\s*to\s*(create|deploy|distribute)\s*(malware|ransomware|virus|trojan|rootkit|keylogger))",
            "severity": "critical",
            "description": "Malware creation instructions",
            "action": "block",
        },
        {
            "name": "exploit_instructions",
            "regex": r"(exploit\s*(development|writing|code)|buffer\s*overflow\s*tutorial|zero[- ]?day\s*(development|exploit))",
            "severity": "high",
            "description": "Exploit development content",
            "action": "block",
        },
        {
            "name": "ransomware_distribution",
            "regex": r"(ransomware\s*(distribution|deployment|as\s*a\s*service)|malware\s*as\s*a\s*service)",
            "severity": "critical",
            "description": "Ransomware distribution",
            "action": "block",
        },
    ],
    "cyberbullying": [
        {
            "name": "cyberbullying_direct",
            "regex": r"(you\s*are\s*(useless|worthless|stupid|ugly|pathetic)|nobody\s*loves\s*you)",
            "severity": "medium",
            "description": "Direct cyberbullying",
            "action": "warn",
        },
        {
            "name": "body_shaming",
            "regex": r"(body\s*shaming|fat\s*(shame|hate)|(you'?re|ur)\s*(so\s*)?(fat|ugly|disgusting))",
            "severity": "medium",
            "description": "Body shaming detected",
            "action": "warn",
        },
    ],
    "misinformation": [
        {
            "name": "health_misinfo",
            "regex": r"(vaccines?\s*cause\s*autism|5g\s*causes\s*cancer|chemtrail|flat\s*earth)",
            "severity": "medium",
            "description": "Health misinformation",
            "action": "warn",
        },
        {
            "name": "election_misinfo",
            "regex": r"(stolen\s*election|rigged\s*election|voter\s*fraud\s*ring|massive\s*voter\s*fraud)",
            "severity": "medium",
            "description": "Election misinformation",
            "action": "warn",
        },
    ],
    "spam": [
        {
            "name": "spam_patterns",
            "regex": r"(click\s*here\s*(to\s*)?(win|claim|get|earn)|buy\s*now|limited\s*time\s*offer|act\s*now)",
            "severity": "low",
            "description": "Spam patterns detected",
            "action": "warn",
        },
    ],
    "human_trafficking": [
        {
            "name": "trafficking_content",
            "regex": r"(human\s*(trafficking|smuggling|slavery)|forced\s*(labor|labour|prostitution))",
            "severity": "critical",
            "description": "Human trafficking content",
            "action": "escalate",
        },
        {
            "name": "forced_marriage",
            "regex": r"(forced\s*marriage|child\s*(bride|marriage)|mail[- ]?order\s*bride)",
            "severity": "critical",
            "description": "Forced marriage content",
            "action": "escalate",
        },
    ],
    "gambling": [
        {
            "name": "gambling_promotion",
            "regex": r"(online\s*(casino|gambling|betting)|sports\s*betting|poker\s*online)",
            "severity": "low",
            "description": "Gambling promotion",
            "action": "warn",
        },
    ],
    "animal_cruelty": [
        {
            "name": "animal_abuse",
            "regex": r"(animal\s*(cruelty|abuse|torture|fighting)|dog\s*fighting|cockfighting)",
            "severity": "high",
            "description": "Animal cruelty content",
            "action": "block",
        },
    ],
    "extremism": [
        {
            "name": "political_extremism",
            "regex": r"(overthrow\s*(government|regime)|violent\s*revolution|armed\s*insurrection)",
            "severity": "high",
            "description": "Political extremism",
            "action": "block",
        },
        {
            "name": "incel_ideology",
            "regex": r"(incel\s*(ideology|revolution|uprising)|black\s*pill|femoid)",
            "severity": "high",
            "description": "Incel extremist ideology",
            "action": "block",
        },
    ],
    "censorship_evasion": [
        {
            "name": "vpn_proxy_promotion",
            "regex": r"(bypass\s*(filter|block|censor|firewall)|unblock\s*(website|site|content))",
            "severity": "low",
            "description": "Censorship evasion promotion",
            "action": "warn",
        },
    ],
}
