"""
Data models for the Rules-Emerging-Pattern system.
"""

from .rule import (
    Rule,
    RuleSet,
    RuleTier,
    RuleType,
    RuleSeverity,
    RuleStatus,
    RulePattern,
    RuleContext,
    RuleEvaluationRequest,
    RuleTemplate,
    RuleGroup,
    RuleSchedule,
    RuleDependency,
    RuleStats,
    EnforcementLevel,
)

from .conflict import (
    RuleConflict,
    ConflictType,
    ConflictSeverity,
    ConflictResolution,
    ResolutionStrategy,
    ConflictAnalysis,
    ConflictResolutionRequest,
    ConflictResolutionResult,
    ConflictPattern,
    ConflictImpact,
    ConflictNotification,
    ConflictAudit,
    ConflictPreventionRule,
)

from .validation import (
    Violation,
    ViolationType,
    ActionTaken,
    Suggestion,
    ValidationResult,
    BatchValidationRequest,
    BatchValidationResult,
    ComplianceReport,
    ValidationProfile,
    ValidationAudit,
    ValidationThreshold,
    ValidationReport,
    ValidationFeedback,
)

from .monitoring import (
    AlertDefinition,
    AlertEvent,
    MonitorConfig,
    MetricsSnapshot,
    MetricsThreshold,
    DashboardConfig,
    DashboardWidget,
    AlertSeverity,
    AlertStatus,
)

from .audit import (
    AuditEvent,
    RuleAuditEvent,
    ViolationAuditEvent,
    ConfigAuditEvent,
    AuditTrail,
    AuditQuery,
    AuditExport,
    AuditPolicy,
    AuditAction,
    AuditCategory,
    AuditSeverity,
)

__all__ = [
    # rule
    "Rule",
    "RuleSet",
    "RuleTier",
    "RuleType",
    "RuleSeverity",
    "RuleStatus",
    "RulePattern",
    "RuleContext",
    "RuleEvaluationRequest",
    "RuleTemplate",
    "RuleGroup",
    "RuleSchedule",
    "RuleDependency",
    "RuleStats",
    "EnforcementLevel",
    # conflict
    "RuleConflict",
    "ConflictType",
    "ConflictSeverity",
    "ConflictResolution",
    "ResolutionStrategy",
    "ConflictAnalysis",
    "ConflictResolutionRequest",
    "ConflictResolutionResult",
    "ConflictPattern",
    "ConflictImpact",
    "ConflictNotification",
    "ConflictAudit",
    "ConflictPreventionRule",
    # validation
    "Violation",
    "ViolationType",
    "ActionTaken",
    "Suggestion",
    "ValidationResult",
    "BatchValidationRequest",
    "BatchValidationResult",
    "ComplianceReport",
    "ValidationProfile",
    "ValidationAudit",
    "ValidationThreshold",
    "ValidationReport",
    "ValidationFeedback",
    # monitoring
    "AlertDefinition",
    "AlertEvent",
    "MonitorConfig",
    "MetricsSnapshot",
    "MetricsThreshold",
    "DashboardConfig",
    "DashboardWidget",
    "AlertSeverity",
    "AlertStatus",
    # audit
    "AuditEvent",
    "RuleAuditEvent",
    "ViolationAuditEvent",
    "ConfigAuditEvent",
    "AuditTrail",
    "AuditQuery",
    "AuditExport",
    "AuditPolicy",
    "AuditAction",
    "AuditCategory",
    "AuditSeverity",
]